server:
  port: 9093
spring:
  application:
    name: link_shortener
  datasource:
    url: jdbc:postgresql://localhost:5432/link_shortenerdb
    username: postgres
    password: gabeman
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


secretJwtString: "jasdvnbonqewierqw0893834030jhferfnwesncdjaskncocqwbjbji"

